### ISSUE TITLE
Save button not working 

### ISSUE THREAD

**Issue by Rovinovic** [blzsaa/reddit-custom-feed-bulk-editor#77]
Saving the feeds added is not reflecting on reddit side.

**Comment by blzsaa** [comment]
Hello,

Thanks for reporting it. 

After some investigation I found out that the issue is CORS related therefore it should be only a problem from a browser.

That in mind here is a quick workaround for chrome:

1. edit your custom feed subscriptions
2. open the devtool and navigate to network tab in your browser
3. now click on save in the UI
4. in the network tab right click on any request -> copy -> copy all as cURL
5. paste in terminal and hit enter

**Comment by doomsday53** [comment]
I tried both bash and cmd cURLs but neither worked on windows terminal. Is there something im missing?

**Comment by blzsaa** [comment]
Alternatively you can temporally disable CORS for the webpage with a CORS disable extension, e.g.  https://mybrowseraddon.com/access-control-allow-origin.html

**Comment by blzsaa** [comment]
I deployed a new version where I have implemented a middleware layer to handle the new CORS settings implemented by Reddit.

Could you please check it if it's working for you?

**Comment by doomsday53** [comment]
Nice it works. Good job!!
